# Generated by Django 3.2.15 on 2022-10-04 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='data_ordered',
            new_name='date_ordered',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='trancaction_id',
            new_name='transaction_id',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='data_added',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='data_added',
            new_name='date_added',
        ),
    ]
