# Generated by Django 3.2.15 on 2022-10-04 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20221004_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='static/placeholder.png', upload_to='blog/'),
        ),
    ]
