# Generated by Django 3.2.15 on 2022-10-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='staticfiles/images/placeholder.png', upload_to='blog/'),
        ),
    ]
